#pragma once
#define CURL_STATICLIB
#include <iostream>
#include <fstream>
#include <vector>
#include <iomanip>
#include <sstream>
#include <vector>
#include <cstring>
#include <locale>
#include <codecvt>
#include <cctype>
#include <array>
#include <ranges>
#include <numeric>
#include <algorithm>
#include <string_view>
#include <Windows.h>
#include <filesystem>
#include <Commdlg.h>
#include <tchar.h>
#include <bitset>
#include <cstdio>
#include <vcclr.h>
#include "curl/curl.h"
#include <thread>
#include <regex>
#include <nlohmann/json.hpp>